const SERVER_URL = import.meta.env.VITE_API_URL || 'https://modi-handloom-site.onrender.com';

const local = (filename) => `${SERVER_URL}/uploads/products/${filename}`;

const products = [
  // ---------- Cotton Fabric ----------
  {
    name: 'Handwoven Kora Cotton — Natural',
    slug: 'handwoven-kora-cotton-natural',
    category: 'Cotton Fabric',
    fabric: '100% Handloom Cotton',
    shortDescription: 'Raw, unbleached handloom cotton with a soft, breathable weave.',
    description:
      'Woven on traditional pit looms by artisan families in Madhya Pradesh, this raw kora cotton keeps its natural, undyed tone. Lightweight and breathable, it is ideal for kurtas, home furnishing and summer layering. Every metre carries the gentle irregularities that mark genuine handloom cloth.',
    images: [local('Handwoven-kora-cotton.png'), local('cotton-charcoal-grey-2.png')],
    price: 420,
    unit: 'per metre',
    colors: ['Natural'],
    stock: 120,
    isFeatured: true,
    weaveType: 'Handwoven',
    origin: 'Maheshwar, Madhya Pradesh',
  },
  {
    name: 'Mul Cotton Fabric — Indigo Blue',
    slug: 'mul-cotton-fabric-indigo-blue',
    category: 'Cotton Fabric',
    fabric: '100% Mul Cotton',
    shortDescription: 'Featherlight mul cotton, naturally dyed in deep indigo.',
    description:
      'Mul cotton is spun fine and woven loose for an airy drape that softens with every wash. This piece is dyed in small indigo vats using a traditional resist process, giving each batch subtle tonal variation. Perfect for dupattas, summer kurtas and lining.',
    images: [local('mul-cotton-indigo-1.jpg'), local('mul-cotton-indigo-2.png')],
    price: 480,
    unit: 'per metre',
    colors: ['Indigo Blue'],
    stock: 95,
    isFeatured: true,
    weaveType: 'Handwoven',
    origin: 'Bhagalpur, Bihar',
  },
  {
    name: 'Chanderi Cotton Fabric — Ivory',
    slug: 'chanderi-cotton-fabric-ivory',
    category: 'Cotton Fabric',
    fabric: 'Cotton-Silk Blend',
    shortDescription: 'The signature sheer, glossy hand of Chanderi weaving.',
    description:
      'Chanderi weavers blend fine cotton with a whisper of silk to give this fabric its characteristic translucence and soft sheen. Traditionally used for festive wear, it drapes beautifully and takes block-printing and embroidery well.',
    images: [local('chanderi-ivory-1.png'), local('chanderi-ivory-2.png')],
    price: 650,
    unit: 'per metre',
    colors: ['Ivory'],
    stock: 60,
    isFeatured: false,
    weaveType: 'Handwoven',
    origin: 'Chanderi, Madhya Pradesh',
  },
  {
    name: 'Khadi Cotton Fabric — Charcoal Grey',
    slug: 'khadi-cotton-fabric-charcoal-grey',
    category: 'Cotton Fabric',
    fabric: '100% Handspun Khadi Cotton',
    shortDescription: 'Hand-spun, hand-woven khadi with a matte, textured finish.',
    description:
      'Spun on the charkha and woven by hand, this khadi cotton carries the slow, deliberate texture that machine cloth cannot replicate. Cooler in summer and warmer in winter than mill-made cotton, it is a favourite for everyday kurtas and jackets.',
    images: [local('cotton-charcoal-grey.jpg'), local('cotton-charcoal-grey-2.jpg')],
    price: 390,
    unit: 'per metre',
    colors: ['Charcoal Grey'],
    stock: 80,
    isFeatured: false,
    weaveType: 'Handspun & Handwoven',
    origin: 'Wardha, Maharashtra',
  },
  {
    name: 'Handloom Cotton Fabric — Madder Stripe',
    slug: 'handloom-cotton-fabric-madder-stripe',
    category: 'Cotton Fabric',
    fabric: '100% Handloom Cotton',
    shortDescription: 'Yarn-dyed stripes in natural madder root red.',
    description:
      'Dyed with madder root before weaving, the yarn carries colour through and through rather than sitting on the surface. Woven into a fine stripe on a traditional handloom, this fabric is durable enough for daily wear and soft enough for infants.',
    images: [local('cotton-madder-stripe.jpg'), local('cotton-madder-stripe-2.jpg')],
    price: 460,
    unit: 'per metre',
    colors: ['Madder Red / Natural'],
    stock: 70,
    isFeatured: false,
    weaveType: 'Handwoven',
    origin: 'Kannur, Kerala',
  },

  // ---------- Poplin Fabric ----------
  {
    name: 'Fine Poplin Fabric — White',
    slug: 'fine-poplin-fabric-white',
    category: 'Poplin Fabric',
    fabric: '100% Cotton Poplin',
    shortDescription: 'Crisp, tight-weave poplin for shirting and formal wear.',
    description:
      'A closely woven plain-weave cotton with a smooth, slightly lustrous finish. This poplin holds a crease well and tailors cleanly, making it the standard choice for shirts, uniforms and structured garments.',
    images: [local('poplin-white-1.webp'), local('poplin-white-2')],
    price: 340,
    unit: 'per metre',
    colors: ['White'],
    stock: 150,
    isFeatured: true,
    weaveType: 'Powerloom',
    origin: 'Erode, Tamil Nadu',
  },
  {
    name: 'Poplin Fabric — Pastel Blue',
    slug: 'poplin-fabric-pastel-blue',
    category: 'Poplin Fabric',
    fabric: '100% Cotton Poplin',
    shortDescription: 'Soft pastel poplin, pre-shrunk and colourfast.',
    description:
      'Pre-shrunk and garment washed for a soft hand-feel straight off the bolt, this poplin holds its pastel blue shade wash after wash. Suited to shirts, dresses and children\u2019s wear.',
    images: [local('poplin blue.jpg'), local('poplin blue (2).jpg')],
    price: 350,
    unit: 'per metre',
    colors: ['Pastel Blue'],
    stock: 110,
    isFeatured: false,
    weaveType: 'Powerloom',
    origin: 'Erode, Tamil Nadu',
  },
  {
    name: 'Yarn-Dyed Poplin Check — Indigo',
    slug: 'yarn-dyed-poplin-check-indigo',
    category: 'Poplin Fabric',
    fabric: '100% Cotton Poplin',
    shortDescription: 'Classic indigo-and-white check, dyed before weaving.',
    description:
      'The check is built into the weave itself, with indigo and white yarns crossing on the loom rather than printed after. A timeless pattern for shirting, table linen and light home furnishing.',
    images: [local('poplin-check-1.jpg'), local('poplin-check-2.jpg')],
    price: 380,
    unit: 'per metre',
    colors: ['Indigo Check'],
    stock: 90,
    isFeatured: false,
    weaveType: 'Powerloom',
    origin: 'Erode, Tamil Nadu',
  },
  {
    name: 'Poplin Fabric — Turmeric Yellow',
    slug: 'poplin-fabric-turmeric-yellow',
    category: 'Poplin Fabric',
    fabric: '100% Cotton Poplin',
    shortDescription: 'A warm, earthy yellow poplin with a smooth finish.',
    description:
      'Dyed in a warm turmeric shade, this poplin brings a pop of colour to shirting and dresses while keeping the crisp hand and easy-iron quality poplin is known for.',
    images: [local('poplin-yellow-1.webp'), local('poplin-yellow-2.webp')],
    price: 350,
    unit: 'per metre',
    colors: ['Turmeric Yellow'],
    stock: 75,
    isFeatured: false,
    weaveType: 'Powerloom',
    origin: 'Erode, Tamil Nadu',
  },

  // ---------- Sarees ----------
  {
    name: 'Maheshwari Handloom Saree — Green Zari',
    slug: 'maheshwari-handloom-saree-green-zari',
    category: 'Sarees',
    fabric: 'Cotton-Silk Blend',
    shortDescription: 'Signature Maheshwari border and reversible pallu.',
    description:
      'Woven on traditional looms in Maheshwar, this saree carries the region\u2019s recognisable striped border and a reversible pallu that can be worn both ways. The cotton-silk blend keeps it light enough for daylong wear.',
    images: [local('maheshwari-saree-1.webp'), local('maheshwari-2'), local('maheshwari-teal-3')],
    price: 3200,
    unit: 'per piece',
    colors: ['Green'],
    stock: 25,
    isFeatured: true,
    weaveType: 'Handwoven',
    origin: 'Maheshwar, Madhya Pradesh',
  },
  {
    name: 'Chanderi Silk Cotton Saree — Ivory Gold',
    slug: 'chanderi-silk-cotton-saree-ivory-gold',
    category: 'Sarees',
    fabric: 'Chanderi Cotton-Silk',
    shortDescription: 'Sheer Chanderi weave with a fine zari border.',
    description:
      'Known for its translucent texture and soft sheen, this Chanderi saree is finished with a delicate zari border. A go-to choice for festive occasions where you want elegance without heaviness.',
    images: [local('chanderi-saree-1.webp'), local('chanderi-saree-2')],
    price: 4500,
    unit: 'per piece',
    colors: ['Ivory Gold'],
    stock: 18,
    isFeatured: true,
    weaveType: 'Handwoven',
    origin: 'Chanderi, Madhya Pradesh',
  },
  {
    name: 'Jamdani Cotton Saree — Off White',
    slug: 'jamdani-cotton-saree-off-white',
    category: 'Sarees',
    fabric: '100% Handloom Cotton',
    shortDescription: 'Hand-woven motifs, worked directly into the weave.',
    description:
      'Jamdani weaving is done entirely by hand, with each motif worked into the fabric thread by thread as it is woven rather than embroidered afterward. This makes every piece genuinely one of a kind.',
    images: [local('jamdani-1.webp'), local('jamdani-2.webp')],
    price: 5200,
    unit: 'per piece',
    colors: ['Off White'],
    stock: 12,
    isFeatured: false,
    weaveType: 'Handwoven',
    origin: 'Shantipur, West Bengal',
  },
  {
    name: 'Kota Doria Saree — Blush Pink',
    slug: 'kota-doria-saree-blush-pink',
    category: 'Sarees',
    fabric: 'Cotton-Silk Doria',
    shortDescription: 'The airy, checkered weave native to Kota.',
    description:
      'Kota Doria is prized for its distinctive square-check weave, called khat, which gives the fabric an open, airy texture. Light enough to wear through a warm afternoon.',
    images: [local('kota-doria-1.webp'), local('kota-doria-2.webp')],
    price: 2800,
    unit: 'per piece',
    colors: ['Blush Pink'],
    stock: 20,
    isFeatured: false,
    weaveType: 'Handwoven',
    origin: 'Kota, Rajasthan',
  },

  // ---------- Home Linen ----------
  {
    name: 'Handloom Cotton Bedsheet Set — Flower Print',
    slug: 'handloom-cotton-bedsheet-flower-print',
    category: 'Home Linen',
    fabric: '100% Handloom Cotton',
    shortDescription: 'Hand block-printed bedsheet with two pillow covers.',
    description:
      'Printed by hand using carved wooden blocks and natural indigo dye, no two sheets are ever quite identical. Set includes one flat bedsheet and two pillow covers, woven in breathable handloom cotton that softens beautifully with washing.',
    images: [local('bedsheet-indigo-1.png'), local('bedsheet-indigo-2')],
    price: 2100,
    unit: 'per set',
    colors: ['Indigo flower Print'],
    stock: 40,
    isFeatured: true,
    weaveType: 'Handwoven, Hand Block-Printed',
    origin: 'Bagru, Rajasthan',
  },
  {
    name: 'Cotton Dohar (Summer Quilt) — Natural Dye',
    slug: 'cotton-dohar-summer-quilt-natural-dye',
    category: 'Home Linen',
    fabric: '100% Handloom Cotton',
    shortDescription: 'Lightweight two-layer quilt, perfect for warm nights.',
    description:
      'A traditional dohar is two layers of handloom cotton stitched together with a simple running quilt pattern, light enough for summer and just warm enough for an air-conditioned room. Dyed with natural pigments.',
    images: [local('dohar-1.png'), local('dohar-2')],
    price: 1800,
    unit: 'per piece',
    colors: ['Natural Dye'],
    stock: 35,
    isFeatured: false,
    weaveType: 'Handwoven',
    origin: 'Barmer, Rajasthan',
  },
  {
    name: 'Handwoven Cushion Covers — Set of 2 — Madder',
    slug: 'handwoven-cushion-covers-set-of-2-madder',
    category: 'Home Linen',
    fabric: '100% Handloom Cotton',
    shortDescription: 'A pair of cushion covers in natural madder red.',
    description:
      'Woven in a plain weave and dyed with madder root, these cushion covers bring a warm, earthy accent to any room. Sold as a pair, with a concealed zip closure.',
    images: [local('cushion-madder-1.png'), local('cushion-madder-2')],
    price: 950,
    unit: 'set of 2',
    colors: ['Madder Red'],
    stock: 55,
    isFeatured: false,
    weaveType: 'Handwoven',
    origin: 'Kannur, Kerala',
  },
  {
    name: 'Cotton Table Runner — Ikat Weave',
    slug: 'cotton-table-runner-ikat-weave',
    category: 'Home Linen',
    fabric: '100% Handloom Cotton',
    shortDescription: 'Resist-dyed ikat pattern, woven not printed.',
    description:
      'In ikat weaving the yarn is tie-dyed before it ever reaches the loom, so the pattern appears with a soft, characteristic blur as it is woven. This table runner brings that texture to your dining table.',
    images: [local('table-runner-ikat-1.png'), local('table-runner-ikat-2')],
    price: 780,
    unit: 'per piece',
    colors: ['Multicolour Ikat'],
    stock: 45,
    isFeatured: false,
    weaveType: 'Handwoven, Ikat',
    origin: 'Pochampally, Telangana',
  },

  // ---------- Stoles & Dupattas ----------
  {
    name: 'Handloom Cotton Stole — Turmeric Yellow',
    slug: 'handloom-cotton-stole-turmeric-yellow',
    category: 'Stoles & Dupattas',
    fabric: '100% Handloom Cotton',
    shortDescription: 'Lightweight everyday stole in warm turmeric yellow.',
    description:
      'A simple, versatile handloom cotton stole finished with hand-twisted tassels at both ends. Light enough for a summer scarf, substantial enough to double as a light shawl.',
    images: [local('stole-yellow-1.jpg'), local('stole-yellow-2.jpg')],
    price: 650,
    unit: 'per piece',
    colors: ['Turmeric Yellow'],
    stock: 65,
    isFeatured: false,
    weaveType: 'Handwoven',
    origin: 'Kannur, Kerala',
  },
  {
    name: 'Chanderi Dupatta — Ivory Zari Border',
    slug: 'chanderi-dupatta-ivory-zari-border',
    category: 'Stoles & Dupattas',
    fabric: 'Chanderi Cotton-Silk',
    shortDescription: 'Sheer dupatta with a fine gold zari border.',
    description:
      'Cut from the same sheer Chanderi cloth used for our sarees, finished with a delicate zari border on both edges. Drapes softly over the shoulder without adding bulk.',
    images: [local('chanderi-dupatta-1.png'), local('chanderi-dupatta-2')],
    price: 1400,
    unit: 'per piece',
    colors: ['Ivory'],
    stock: 30,
    isFeatured: true,
    weaveType: 'Handwoven',
    origin: 'Chanderi, Madhya Pradesh',
  },
  {
    name: 'Khadi Cotton Stole — Charcoal',
    slug: 'khadi-cotton-stole-charcoal',
    category: 'Stoles & Dupattas',
    fabric: '100% Handspun Khadi Cotton',
    shortDescription: 'Hand-spun khadi stole with a soft, matte texture.',
    description:
      'Spun and woven entirely by hand, this khadi stole has a slightly nubby, matte texture that mill cloth cannot replicate. A quiet, everyday accessory that pairs with almost anything.',
    images: [local('khadi-stole-1.jpg'), local('khadi-stole-1.jpg')],
    price: 590,
    unit: 'per piece',
    colors: ['Charcoal'],
    stock: 50,
    isFeatured: false,
    weaveType: 'Handspun & Handwoven',
    origin: 'Wardha, Maharashtra',
  },

  // ---------- Ready to Wear ----------
  {
    name: 'Handloom Cotton Kurta — Natural',
    slug: 'handloom-cotton-kurta-natural',
    category: 'Ready to Wear',
    fabric: '100% Handloom Cotton',
    shortDescription: 'Relaxed-fit kurta cut from raw kora cotton.',
    description:
      'A relaxed, straight-cut kurta made from our handwoven kora cotton, left in its natural undyed shade. Side slits and a mandarin collar keep it easy to move in and easy to style.',
    images: [local('kurta-natural-1.png'), local('kurta-natural-2')],
    price: 1650,
    unit: 'per piece',
    colors: ['Natural'],
    stock: 40,
    isFeatured: true,
    weaveType: 'Handwoven',
    origin: 'Maheshwar, Madhya Pradesh',
  },
  {
    name: 'Poplin Shirt — Indigo Blue',
    slug: 'poplin-shirt-indigo-blue',
    category: 'Ready to Wear',
    fabric: '100% Cotton Poplin',
    shortDescription: 'A tailored everyday shirt in crisp indigo poplin.',
    description:
      'Cut from our fine cotton poplin in a clean, tailored fit, with a button-down collar and single chest pocket. Holds its shape through a full day and irons easily.',
    images: [local('poplin-shirt-1.webp'), local('poplin-shirt-2.webp')],
    price: 1450,
    unit: 'per piece',
    colors: ['Indigo Blue'],
    stock: 48,
    isFeatured: false,
    weaveType: 'Powerloom',
    origin: 'Erode, Tamil Nadu',
  },
  {
    name: 'Handwoven Cotton Jacket — Charcoal',
    slug: 'handwoven-cotton-jacket-charcoal',
    category: 'Ready to Wear',
    fabric: '100% Handspun Khadi Cotton',
    shortDescription: 'An unlined, layerable jacket in textured khadi.',
    description:
      'A simple unstructured jacket cut from hand-spun khadi cotton, left unlined so the natural texture of the weave stays close to the skin. Works as a light layer through most of the year.',
    images: [local('khadi-jacket-1.avif'), local('khadi-jacket-2.avif')],
    price: 2400,
    unit: 'per piece',
    colors: ['Charcoal'],
    stock: 22,
    isFeatured: false,
    weaveType: 'Handspun & Handwoven',
    origin: 'Wardha, Maharashtra',
  },
];

export default products;
